In [1]:
import pandas as pd

In [13]:
df = pd.read_parquet("train.parquet")

In [16]:
df.head()

,user_id,streamer_id,label,retr_score,bpr_score,sasrec_score,trans_score,is_repeat
0,1000015,4900393,1,0.998932,11.889553,11.135473,0.402870,1
1,1000015,5508184,0,0.997740,NaN,3.575213,0.006092,0
2,1000015,6124727,0,0.997538,NaN,NaN,-0.130187,0
3,1000015,1437043,0,0.997482,4.538433,3.919652,-0.227043,0
4,1000015,5469400,0,0.997376,5.457518,5.237952,-0.040929,0

In [14]:
df[(df["label"] == 1) & (df["is_repeat"] == 0)]

,user_id,streamer_id,label,retr_score,bpr_score,sasrec_score,trans_score,is_repeat
836,1000033,6720569,1,0.989416,6.537141,6.402361,NaN,0
3501,1001629,4274339,1,NaN,NaN,NaN,NaN,0
4002,1001637,1002351,1,NaN,NaN,NaN,NaN,0
5503,1001766,6818099,1,NaN,NaN,NaN,NaN,0
8397,1002482,1249595,1,0.988637,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...
3428545,6830085,6720569,1,0.997676,10.678811,1.876652,2.256603,0
3429065,6830305,5915809,1,0.993736,5.827825,2.943481,-0.874124,0
3429956,6830542,1480741,1,0.988566,NaN,NaN,NaN,0
3430540,6831066,6378687,1,NaN,NaN,NaN,NaN,0
3430675,6833090,6539446,1,0.992078,NaN,3.882838,NaN,0

In [17]:
streamer_ids = df["streamer_id"].tolist()

feats = df[
    (df["user_id"] == 1000033) &
    (df["streamer_id"].isin(streamer_ids))
].copy()

In [18]:
feats

,user_id,streamer_id,label,retr_score,bpr_score,sasrec_score,trans_score,is_repeat
500,1000033,4282279,0,0.998049,6.478962,NaN,-0.058262,0
501,1000033,6541071,0,0.997483,4.814514,NaN,-0.668468,0
502,1000033,5169058,0,0.997434,7.143777,3.468506,-0.076873,1
503,1000033,1449113,0,0.997279,6.253945,NaN,-0.388756,0
504,1000033,6203923,0,0.997141,NaN,NaN,-0.895579,0
...,...,...,...,...,...,...,...,...
995,1000033,4663738,0,0.986958,NaN,NaN,NaN,0
996,1000033,6195948,0,0.986952,4.349720,NaN,NaN,0
997,1000033,5282598,0,0.986939,NaN,NaN,NaN,0
998,1000033,6759175,0,0.986936,NaN,NaN,NaN,0
999,1000033,1890951,0,0.986922,NaN,NaN,NaN,0

In [10]:
import json

with open("/nas02/home/kevin/recsys_pipeline/results/retrieval/MiniLM_40epoch_ts_heavy/user_1000015.json", "r") as f:
    raw = json.load(f)
raw_df = pd.DataFrame(raw)

In [11]:
raw_df

     streamer_id     score
0        4900393  0.998932
1        5508184  0.997740
2        6124727  0.997538
3        1437043  0.997482
4        5469400  0.997376
..           ...       ...
495      5871418  0.984172
496      6643109  0.984171
497      5971062  0.984160
498      6513433  0.984140
499      6745876  0.984132

[500 rows x 2 columns]